### ISSUE TITLE
Create Account - Back button and gender page issue.

### ISSUE THREAD

**Issue by priyanka-5305** [criteriontechFlutter/nativevitalio#102]
1. When user click back button they navigate to the UHID page again.
2. Progress bar is showing wrong data and wrong text.
3. User should not navigate to the next page. Gender is mandatory.
4. Skip button missing.

**Steps to Reproduce**
1. Go to the gender page
2. Click back button which is present in the top left corner.
3. User navigates to the UHID page/Login page

**Actual Result**
Back button is not working properly. Clicking the back button navigates user to the UHID page.

**Expected Result**
1. Back button should not navigate the user to the login page.
2. Progress bar should show correct data and correct text.
3. User should not navigate to the next page. Gender is mandatory.
4. Skip button should be present.

![Image](https://github.com/user-attachments/assets/a9024e3b-8db8-491a-8fb0-ad9b2e120dc4)

**Comment by baqar72** [comment]
fixed

**Comment by priyanka-5305** [comment]
Back button should not navigate the user to the login page. ✔ 
Progress bar should show correct data and correct text. ❌ 
Progress bar does not match the figma progress bar and android bar.
![Image](https://github.com/user-attachments/assets/6e9b3b0a-10ff-4f3a-9262-008800448d26)

![Image](https://github.com/user-attachments/assets/0d9eb35b-5043-45f7-9db8-4ddffac66f6e)

User should not navigate to the next page. Gender is mandatory.✔ 
Skip button should be present.✔

**Comment by priyanka-5305** [comment]
Not fixed 

1. Set vital reminder and fluid intake detail progress bar has different percentage. 

Set Vital Reminder
<img width="350" height="639" alt="Image" src="https://github.com/user-attachments/assets/f37a65b4-4717-4f1a-9450-fc6fca673742" /><img width="292" height="558" alt="Image" src="https://github.com/user-attachments/assets/68d44bd5-2aa7-4825-9183-701a4d081ad1" />

Fluid Intake Detail

<img width="323" height="627" alt="Image" src="https://github.com/user-attachments/assets/3dc355f1-6021-438e-a02c-fe2b66a94280" />

<img width="293" height="559" alt="Image" src="https://github.com/user-attachments/assets/78e07292-743c-4fe3-bb26-4f726a396783" />

2. Full check mark is not visible. some space is left after other.

<img width="285" height="588" alt="Image" src="https://github.com/user-attachments/assets/a6ea7df6-bce0-42c8-a5c7-4812dcdc3a05" />
