### ISSUE TITLE
OTP is not send to the registered user.

### ISSUE THREAD

**Issue by priyanka-5305** [criteriontechFlutter/nativevitalio#109]
When user clicks forget password and enter the mobile number than they did not receive any OTP  in the registered mobile.

**Steps to Reproduce**
1. Go to the Login page
2. Click Forget Password 
3. Enter the registered mobile number
4. Click Get otp button.

**Actual Result**
User is not receiving any OTP messages in the registered mobile number.

**Expected Result** 
User should get the OTP to change the password in the registered mobile number.

![Image](https://github.com/user-attachments/assets/c46bf73d-eea6-4444-b487-c9dd59705458)

**Comment by priyanka-5305** [comment]
@YasirKhan1999 
Getting OTP if I enter the registration number but when I click resend then a error message populates.

![Image](https://github.com/user-attachments/assets/0a3fe02b-dec8-489e-a910-87d498cee416)

**Comment by CTAmitTripathi** [comment]
done

**Comment by priyanka-5305** [comment]
Not fixed.
User is able to resend the otp again after entering the correct otp and verify it.

![Image](https://github.com/user-attachments/assets/0f6779e7-e080-49b0-b03f-83ee2408e9cb)

![Image](https://github.com/user-attachments/assets/30b0d977-f5d5-4030-83c2-7320d549b6bb)
Close the popup message. and again click resend button

![Image](https://github.com/user-attachments/assets/ed5ab2d3-bf1c-4e34-8973-3510387937f7)
