### ISSUE TITLE
Not able to create patient from IOS device.

### ISSUE THREAD

**Issue by priyanka-5305** [criteriontechFlutter/nativevitalio#136]
Not able to create a patient. Entered all the details and clicked next/Skip button under the fluid page but not able to go to dashboard.

Steps to reproduce
1. Go to login page
2. Enter phone number and proceed with all the pages further 
3. enter the data and go to last page
4. click next button or skip button in the fluid page

Actual result
Not able to create patient account

Expected Result
User should be able to create new patient through registration process

![Image](https://github.com/user-attachments/assets/236479e3-b0cc-4980-8084-74fd8b4179ca)

**Comment by baqar72** [comment]
fixed

**Comment by baqar72** [comment]
fixed

**Comment by priyanka-5305** [comment]
**Not fixed**

Still this screen is populating.
<img width="286" height="552" alt="Image" src="https://github.com/user-attachments/assets/816b4153-1ca9-4048-ab4c-e7a4114dc81d" />

Clicked retry button then below screen populate.
It should directly navigate user to the dashboard. Here user have to click "Go to Dashboard" button.

<img width="291" height="544" alt="Image" src="https://github.com/user-attachments/assets/fb20a0dd-c0c6-4d68-a361-678bafe76b3d" />

**Comment by baqar72** [comment]
fixed
