### ISSUE TITLE
Wrong error message when user enter invalid otp.

### ISSUE THREAD

**Issue by priyanka-5305** [criteriontechFlutter/nativevitalio#146]
User enter invalid opt and the error message which they receive is wrong

Steps to Reproduce

1. Click forget password in the login page.
2. enter registration number
3. Click get otp
4. enter wrong otp and click Verify button

Actual Result
The error message is showing "Something went wrong".

Expected Result
The error message should show "Invalid OTP. Please try again."

![Image](https://github.com/user-attachments/assets/df59b56a-9d4d-4124-8315-57a1518333ef)

**Comment by CTAmitTripathi** [comment]
done

**Comment by priyanka-5305** [comment]
Not fixed
Wrong message - It should be "Invalid OTP. Please try again."

![Image](https://github.com/user-attachments/assets/4a9608be-8f6d-411f-9a49-6f56410ff198)

**Comment by priyanka-5305** [comment]
Fixed

Invalid OTP error message is populating.

<img width="1439" height="735" alt="Image" src="https://github.com/user-attachments/assets/3de09e7a-0730-481c-9c0e-1d35c0cac520" />
