### ISSUE TITLE
If user logout and again sign up from different number then they navigate to the previous account.

### ISSUE THREAD

**Issue by priyanka-5305** [criteriontechFlutter/nativevitalio#170]
Steps to Reproduce
1. Create a patient account
2. Logout from the device
3. Again enter new mobile number
4. Enter otp and click Verify button.

Actual Result
User is navigating to the previous page

Expected Result
User should navigate to create account page.

<img width="284" height="546" alt="Image" src="https://github.com/user-attachments/assets/7d279d08-ac91-4c83-92f4-c99550c0c7d0" />

Also, previous number is saved when user logout from the app.
<img width="285" height="523" alt="Image" src="https://github.com/user-attachments/assets/e9f8a551-142a-45b4-bd06-1403d6fb0504" />

<img width="288" height="567" alt="Image" src="https://github.com/user-attachments/assets/22cb0e95-d971-411c-8b29-ccbb36b89bac" />

<img width="289" height="547" alt="Image" src="https://github.com/user-attachments/assets/6e6a1f2b-e486-4ee4-b115-21e6bbfe4788" />

**Comment by baqar72** [comment]
fixed

**Comment by priyanka-5305** [comment]
Not fixed.

Number is populating now also.
and when I try to enter by using UHID then user is navigating to the create account page.

<img width="287" height="587" alt="Image" src="https://github.com/user-attachments/assets/adcb2eb4-5c1a-4cb3-8381-73a56677ee04" />

<img width="291" height="582" alt="Image" src="https://github.com/user-attachments/assets/fa388ced-bcbb-4dab-aaab-1ffb6c7ba8cc" />
