### ISSUE TITLE
Dashboard - Vitals are not visible in the dashboard page.

### ISSUE THREAD

**Issue by priyanka-5305** [criteriontechFlutter/nativevitalio#174]
Vitals are not visible in the dashboard page.

Steps to reproduce
1. Create a patient account
2. Go to dashboard

Actual Result
Vitals section is not populating

Expected Result

Vitals should be visible.

<img width="285" height="531" alt="Image" src="https://github.com/user-attachments/assets/83dba167-a55a-49ed-b85b-ff68a24bc7d8" />

**Comment by baqar72** [comment]
fixed

**Comment by baqar72** [comment]
fixed

**Comment by priyanka-5305** [comment]
Not fixed

1. Vital section is populating in dashboard but it has same symbols for every vital name.
2. Upload section is covering large space. (It should be same as other sections
3. Chat does not have any icon.

<img width="292" height="633" alt="Image" src="https://github.com/user-attachments/assets/8040d6ab-6da7-4a93-ac06-cedddd2459fb" />
