### ISSUE TITLE
Lab Report - Records are not updating

### ISSUE THREAD

**Issue by priyanka-5305** [criteriontechFlutter/nativevitalio#25]
User uploads the report but under Radiology/ Imaging/ Lab record number is showing 0 records.

**Steps to Reproduce**
1. Go to Lab Report Page
2. Click "Add Report"
3. Enter the details and upload the report
4. Go to Radiology/ Imaging/ Lab 

**Actual Result**
0 records is visible in the screen

**Expected Result**
Application should show the number of records which are present in that section.

![Image](https://github.com/user-attachments/assets/bf57ea68-3c1e-4a9d-8965-e2a9f5693c2a)

**Comment by devAtCriteriontech** [comment]
fixed

**Comment by priyanka-5305** [comment]
**Not Fixed** @devAtCriteriontech 

Try to upload the report but in report page noting populates. also Report Parsed is populating.

![Image](https://github.com/user-attachments/assets/083cfac4-c218-48b0-acf7-cfb056da0d3f)

![Image](https://github.com/user-attachments/assets/b231039f-0a8a-4b10-8d18-69b29c16a70c)

![Image](https://github.com/user-attachments/assets/bf06ab16-da86-4ed3-b4fe-d47118695972)

![Image](https://github.com/user-attachments/assets/26efe792-e872-4ba2-9b96-aecc5f32b6ee)
