### ISSUE TITLE
Symptom History - Daily, Weekly and Monthly navigation not working properly

### ISSUE THREAD

**Issue by priyanka-5305** [criteriontechFlutter/nativevitalio#36]
Sometimes when user try to navigate from daily to monthly or weekly the date below does not change and data also does not change.

**Steps to Reproduce**
1. Go to Dashboard
2. Click Symptom Tracker
3. Click Symptom History
4. Now try to navigate between daily, weekly and monthly tabs for few time

**Actual Result**
For first few time the navigation between the tabs works but after that the date does not change

**Expected Result**
User should able to freely navigate between the daily, weekly and monthly tabs with their data.

![Image](https://github.com/user-attachments/assets/9e518e49-733d-40ea-a2a9-367757da8926)

![Image](https://github.com/user-attachments/assets/604456dc-3f53-4d21-9751-7232ccdaf7a5)

**Comment by devAtCriteriontech** [comment]
fixed

**Comment by priyanka-5305** [comment]
**Not Fixed**
By default, weekly is showing but that is not selected.
Daily should be populate when use enters the data.

![Image](https://github.com/user-attachments/assets/b8f50807-8bb9-4b4e-a157-01458483100c)

**Comment by devAtCriteriontech** [comment]
fixed

**Comment by devAtCriteriontech** [comment]
fixed

**Comment by priyanka-5305** [comment]
Fixed
Now symptoms are populating with correct dates

![Image](https://github.com/user-attachments/assets/89aea0b3-e827-48ae-a4c2-9e504f8d460b)

![Image](https://github.com/user-attachments/assets/1c55af8c-ca90-497a-9e51-4339f5def81e)

![Image](https://github.com/user-attachments/assets/2aa4a0bb-54c5-4ef0-8f16-504e27d8d270)
