### ISSUE TITLE
Emergency Contact - Fields are accepting different values

### ISSUE THREAD

**Issue by priyanka-5305** [criteriontechFlutter/nativevitalio#39]
User can enter emoji, number, spaces and special characters in the Full name field and in the contacts
Father is default value in the Relationship field. 

**Steps to Reproduce**
1. Go to Emergency Contact page
2. Click "Add Contact" button
3. Enter numbers, spaces and special symbols in the full name and contact field

**Actual Result**
Fields are accepting every possible values

**Expected Result**
1. Name field should accept alphabets only
2. Contact fields should accept numbers only
3. In relationship field, please select the relationship should be default value

![Image](https://github.com/user-attachments/assets/b41718cc-82d7-417a-883b-2a57ce9fb61d)

![Image](https://github.com/user-attachments/assets/e3fee7a0-52a5-4d23-bbb0-773d09d063a3)

**Comment by devAtCriteriontech** [comment]
fixed

**Comment by devAtCriteriontech** [comment]
fixed

**Comment by devAtCriteriontech** [comment]
fixed

**Comment by priyanka-5305** [comment]
Not fixed
Only numbers is accepting in the number field but data is not populating.

![Image](https://github.com/user-attachments/assets/fdab82d8-495b-444a-be63-420e0c930595)

![Image](https://github.com/user-attachments/assets/c08d6257-5ae7-4cbb-8f8b-64311b9830b5)

**Comment by AnimeshCriterion** [comment]
@priyanka-5305 Rsolved

**Comment by priyanka-5305** [comment]
Fixed
emergency contacts are visible.
<img width="308" height="636" alt="Image" src="https://github.com/user-attachments/assets/cb2c2aaa-72e4-40e4-98de-39a01b4712b7" />
