### ISSUE TITLE
Dashboard - Upload Reports is not fully visible

### ISSUE THREAD

**Issue by priyanka-5305** [criteriontechFlutter/nativevitalio#4]
Upload reports section is not fully visible in the screen.

**Steps to Reproduce:**

1.Go to dashboard 
2. Upload report is not fully visible

Expected Behaviour:
The section should be normally visible to the user

Actual Behaviour:
The Upload report section is not fully visible to the user

![Image](https://github.com/user-attachments/assets/16d86c12-f92c-4bfb-b3da-ef43e48a596f)

**Comment by devAtCriteriontech** [comment]
fixed

**Comment by priyanka-5305** [comment]
Not fixed
This is full length now.
![Image](https://github.com/user-attachments/assets/23ea9afc-8259-4593-ab0f-fb1ac49e82cb)
