### ISSUE TITLE
Crew Shift Planner and Doctor Schedule Planner date issue

### ISSUE THREAD

**Issue by priyanka-5305** [criteriontechFlutter/nativevitalio#45]
User should not able to see the previous week planner.
Back arrow button should be disabled.

**Steps to Reproduce**
1. Go to Crew Shift Planner/Doctor Schedule Planner
2. Click the back arrow to see the previous schedule planner

**Actual Result**
User is able to go to the previous week planner

**Expected Result** 
User should not able to go to the previous week planner.

![Image](https://github.com/user-attachments/assets/f55a7dca-d8be-44e3-ab98-ddc7b9670de2)

**Comment by CTAmitTripathi** [comment]
done on both nurse and doctor

**Comment by priyanka-5305** [comment]
@CTAmitTripathi  Not fixed

![Image](https://github.com/user-attachments/assets/a142eaf7-b2c6-4932-8f6e-100fbdb41cdd)

**Comment by priyanka-5305** [comment]
@CTAmitTripathi 
**Fixed** 
Not able to go to the previous week data
![Image](https://github.com/user-attachments/assets/4acb4658-bd2c-450f-8c5d-91b0b5287805)
