### ISSUE TITLE
Masters - Not able to create shifts

### ISSUE THREAD

**Issue by priyanka-5305** [criteriontechFlutter/nativevitalio#47]
User is not able to create shifts.

Steps to Reproduce
1. Go to Masters
2. Enter the details under shift tab

Actual Result
User is not able to add Shifts

Expected Result
User should be able to create the Shifts 

![Image](https://github.com/user-attachments/assets/c5316537-a653-4d4e-bbf8-8d259843b371)

**Comment by YasirKhan1999** [comment]
@CTAmitTripathi API is working, plz check on your side.

**Comment by CTAmitTripathi** [comment]
done

**Comment by priyanka-5305** [comment]
@CTAmitTripathi Not fixed
Tried to create below data but the error is populating.
![Image](https://github.com/user-attachments/assets/af348696-6669-45d9-94bf-6bfd6a119e4f)

**Comment by CTAmitTripathi** [comment]
done
