### ISSUE TITLE
Create Crew - The shifts fields should not be mandatory fields

### ISSUE THREAD

**Issue by priyanka-5305** [criteriontechFlutter/nativevitalio#52]
While creating the crew shift and doctors shifts, the shifts fields should not be mandatory

**Steps to Reproduce**
1. Go to Crew Shift Planner/Doctor Schedule Planner
2. Create a crew

**Actual Result**
Shift fields are mandatory 

**Expected Result**
Shift Fields should not be mandatory

![Image](https://github.com/user-attachments/assets/50f50fc2-4d4c-40fd-b508-ea0680409f1d)

**Comment by CTAmitTripathi** [comment]
done

**Comment by priyanka-5305** [comment]
@CTAmitTripathi 
Issue is not fixed.
When I click apply without selecting any crew member then a error message populates.
![Image](https://github.com/user-attachments/assets/554b9368-b38f-4b1d-9328-cd38cb6ef61f)

**Comment by priyanka-5305** [comment]
@CTAmitTripathi mandatory fields should be removed in doctor schedule planner also.

![Image](https://github.com/user-attachments/assets/ce4d8261-60ec-4997-833e-397412b94157)

**Comment by priyanka-5305** [comment]
Mandatory icon is removed - Fixed
![Image](https://github.com/user-attachments/assets/b44a07e2-a27e-408a-b373-3344529ea1fc)
