### ISSUE TITLE
Not able to add crew

### ISSUE THREAD

**Issue by priyanka-5305** [criteriontechFlutter/nativevitalio#53]
User is not able to add crew 

**Steps to Reproduce**
1. Go to Crew Shift Planner
2. Click "Add New Crew" button

**Actual** Result
User is not able to add new crew

**Expected Result**
User should able to add new crew

![Image](https://github.com/user-attachments/assets/885c1e88-ba53-4339-9e80-74b007e15a3e)

**Comment by CTAmitTripathi** [comment]
done

**Comment by priyanka-5305** [comment]
@CTAmitTripathi 
User is able to create the crew but the create button does not disappear when the crew is created.
After creating the crew, the buttons and the three dots should disappear. 

![Image](https://github.com/user-attachments/assets/b982b240-6ed2-4465-b042-6889be8bfa35)

**Comment by priyanka-5305** [comment]
@CTAmitTripathi **Not fixed**
Disabled the crew 6 and enable the crew 7 in the master page but in the crew shift planner crew 6 is still populating and crew 7 is not  visible.

![Image](https://github.com/user-attachments/assets/98c72e7b-ba96-47aa-959b-f3b36465df7a)

![Image](https://github.com/user-attachments/assets/b4041918-e2f8-468e-a990-98ebae9bc316)

**Comment by priyanka-5305** [comment]
Able to  create the crew and when enable or disable the crew it reflects in the Crew Shift Planner. ✔ 
The successful message appears for only 1 second.  ❌ 

![Image](https://github.com/user-attachments/assets/0255fdde-80cd-4497-b7a0-42c414cb33a4)
