### ISSUE TITLE
Skip is not working.

### ISSUE THREAD

**Issue by priyanka-5305** [criteriontechFlutter/nativevitalio#57]
User is not able to skip the pages.

**Steps to Reproduce**
1. Go to Create Account
2. Enter the details and click next
3. Click Skip on the top right corner

**Actual Result**
Skip is not working

**Expected Result**
Skip should be disabled in the Name, Gender and Date of Birth page. 
Except these pages skip should be enabled.

![Image](https://github.com/user-attachments/assets/cfa56da8-6dce-4634-83f0-94652fc8bcae)

**Comment by devAtCriteriontech** [comment]
fixed

**Comment by priyanka-5305** [comment]
Not Fixed ❌ 

1. User should be able to skip from Blood group page but right now user can skip from Weight page.
2. also skip should be disabled in the colour so that user know that the skip is disabled.
3. Preview page, Set Preference page should not have skip hyperlink.
4. Clicking the  skip button in the fluid intake page redirects the user to the verification page.

![Image](https://github.com/user-attachments/assets/819e32c9-d4c3-457e-846b-12217967f09a)

![Image](https://github.com/user-attachments/assets/8ad9e117-5deb-46ab-b95c-7bfe63be72e3)

**Comment by devAtCriteriontech** [comment]
fixed

**Comment by priyanka-5305** [comment]
**Fixed**
1. User should be able to skip from Blood group page but right now user can skip from Weight page. ❌ 
2. also skip should be disabled in the colour so that user know that the skip is disabled. ✔ 
3. Preview page, Set Preference page should not have skip hyperlink. ✔ (It is disabled )
4. Clicking the skip button in the fluid intake page redirects the user to the verification page. ✔ 
5. Also Set Preference page does not have progress bar. ✔
