### ISSUE TITLE
User profile - User is not able to upload profile picture

### ISSUE THREAD

**Issue by priyanka-5305** [criteriontechFlutter/nativevitalio#8]
User is not able to upload a profile picture more than 10 mb.

**Steps to Reproduce**

1. Go to dashboard
2. Go to menu
3. Upload a pic of more than 10mb

Expected result
Profile picture should be uploaded 

Actual result
Profile picture is not uploading

**Comment by devAtCriteriontech** [comment]
fixed

**Comment by AnimeshCriterion** [comment]
@priyanka-5305  PLEASE CLOSE IF VERIFIED

**Comment by priyanka-5305** [comment]
**Not Fixed**
Adding a image of  more than 10mb closes the application

![Image](https://github.com/user-attachments/assets/b9c0bbb6-3b5d-4ac5-9e8f-753cb96affc7)
